export * from './src/auth/mod.ts'
export * from './src/cache/mod.ts'
export * from './src/capabilities/mod.ts'
export * from './src/connection/mod.ts'
export * from './src/crud/mod.ts'
export * from './src/migration/mod.ts'
export * from './src/orchestration/mod.ts'
export * from './src/query/mod.ts'
export * from './src/schema/mod.ts'
export * from './src/utils/mod.ts'
export * from './src/client.ts'
export * from './src/constants.ts'
export * from './src/settings.ts'
export * from './src/types/mod.ts'

/** SurrealDB v2 types for convenience */
export { RecordId, SurrealError, Table } from 'surrealdb'
